from django.urls import path

from .views import (
    UserRegistrationView,
    app_settings,
    device_dns_activity,
    dns_activity,
    dns_unmatched_clients,
    UserLoginView,
    UserLogoutView,
    setup_status,
    version_status,
    device,
    device_availability,
    bulk_update_devices,
    device_web_interface,
    events,
    scan_now,
    scan_runs,
    scan_status,
    notifications,
    export_devices,
    export_diagnostics,
    health_status,
    home_map_layout,
    import_devices,
    import_netalertx_devices,
    import_watchyourlan_devices,
    maintenance_cleanup,
    test_notification_channel,
    sync_adguard,
    test_adguard,
    speedtest_tracker_latest,
    test_speedtest_tracker,
    users,
)

urlpatterns = [
    path("health/", health_status, name="health-status"),
    path("register/", UserRegistrationView.as_view(), name="register"),
    path("setup/", setup_status, name="setup-status"),
    path("version/", version_status, name="version-status"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("users/", users, name="users"),
    path("settings/", app_settings, name="app-settings"),
    path("integrations/adguard/test/", test_adguard, name="test-adguard"),
    path("integrations/adguard/sync/", sync_adguard, name="sync-adguard"),
    path(
        "integrations/speedtest-tracker/test/",
        test_speedtest_tracker,
        name="test-speedtest-tracker",
    ),
    path(
        "integrations/speedtest-tracker/latest/",
        speedtest_tracker_latest,
        name="speedtest-tracker-latest",
    ),
    path(
        "notifications/test/",
        test_notification_channel,
        name="test-notification-channel",
    ),
    path("home-map-layout/", home_map_layout, name="home-map-layout"),
    path("maintenance/cleanup/", maintenance_cleanup, name="maintenance-cleanup"),
    path("device/", device, name="device"),
    path("device/availability/", device_availability, name="device-availability"),
    path("devices/bulk-update/", bulk_update_devices, name="bulk-update-devices"),
    path("device/web-interface/", device_web_interface, name="device-web-interface"),
    path("device/dns-activity/", device_dns_activity, name="device-dns-activity"),
    path("dns-activity/", dns_activity, name="dns-activity"),
    path(
        "dns-activity/unmatched/",
        dns_unmatched_clients,
        name="dns-unmatched-clients",
    ),
    path("scan/", scan_now, name="scan_now"),
    path("scan/status/", scan_status, name="scan_status"),
    path("scan/runs/", scan_runs, name="scan_runs"),
    path("events/", events, name="events"),
    path("notifications/", notifications, name="notifications"),
    path("devices/export/", export_devices, name="export_devices"),
    path("diagnostics/export/", export_diagnostics, name="export_diagnostics"),
    path("devices/import/", import_devices, name="import_devices"),
    path(
        "devices/import/netalertx/",
        import_netalertx_devices,
        name="import_netalertx_devices",
    ),
    path(
        "devices/import/watchyourlan/",
        import_watchyourlan_devices,
        name="import_watchyourlan_devices",
    ),
]
