from django.urls import path

from .views import (
    UserRegistrationView,
    app_settings,
    UserLoginView,
    UserEditView,
    UserLogoutView,
    setup_status,
    version_status,
    device,
    device_web_interface,
    events,
    scan_now,
    scan_runs,
    scan_status,
    notifications,
    export_db,
    import_db,
    export_devices,
    health_status,
    home_map_layout,
    import_devices,
    import_watchyourlan_devices,
    maintenance_cleanup,
    test_notification_channel,
    users,
)

urlpatterns = [
    path("health/", health_status, name="health-status"),
    path("register/", UserRegistrationView.as_view(), name="register"),
    path("setup/", setup_status, name="setup-status"),
    path("version/", version_status, name="version-status"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("edit/", UserEditView.as_view(), name="user-edit"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("users/", users, name="users"),
    path("settings/", app_settings, name="app-settings"),
    path(
        "notifications/test/",
        test_notification_channel,
        name="test-notification-channel",
    ),
    path("home-map-layout/", home_map_layout, name="home-map-layout"),
    path("maintenance/cleanup/", maintenance_cleanup, name="maintenance-cleanup"),
    path("device/", device, name="device"),
    path("device/web-interface/", device_web_interface, name="device-web-interface"),
    path("scan/", scan_now, name="scan_now"),
    path("scan/status/", scan_status, name="scan_status"),
    path("scan/runs/", scan_runs, name="scan_runs"),
    path("events/", events, name="events"),
    path("notifications/", notifications, name="notifications"),
    path("devices/export/", export_devices, name="export_devices"),
    path("devices/import/", import_devices, name="import_devices"),
    path(
        "devices/import/watchyourlan/",
        import_watchyourlan_devices,
        name="import_watchyourlan_devices",
    ),
    path("export-db/", export_db, name="export_db"),
    path("import-db/", import_db, name="import_db"),
]
