services:
  backend:
    volumes:
      - static:/static
      - database:/data
    env_file:
      - .env
    environment:
      DB_PATH: /data/db.sqlite3
    build:
      context: .
    ports:
      - '8000:8000'
    privileged: true
  scanner:
    volumes:
      - static:/static
      - database:/data
    env_file:
      - .env
    environment:
      DB_PATH: /data/db.sqlite3
    build:
      context: .
    command: ["python", "manage.py", "run_scheduler"]
    privileged: true
    depends_on:
      - backend
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/app/build
  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - '80:80'
    depends_on:
      - backend
      - frontend

volumes:
  static:
  database:
  frontend:
