"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()


UNSAFE_SECRET_KEYS = {
    "",
    "change-me",
    "unsafe-dev-secret-key",
}


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=None, cast=str):
    value = os.getenv(name)
    if not value:
        return default or []
    return [cast(item.strip()) for item in value.split(",") if item.strip()]


def validate_production_settings(environment, secret_key, debug, allowed_hosts):
    if environment != "production":
        return

    errors = []
    if secret_key in UNSAFE_SECRET_KEYS or len(secret_key) < 32:
        errors.append("SECRET_KEY must be set to a strong unique value.")
    if debug:
        errors.append("DEBUG must be false.")
    if not allowed_hosts:
        errors.append("ALLOWED_HOSTS must include at least one host.")
    if "*" in allowed_hosts:
        errors.append("ALLOWED_HOSTS must not contain '*'.")

    localhost_hosts = {"localhost", "127.0.0.1", "[::1]"}
    if set(allowed_hosts).issubset(localhost_hosts):
        errors.append("ALLOWED_HOSTS must include the LAN IP, hostname, or domain.")

    if errors:
        raise ImproperlyConfigured(
            "Invalid production configuration: " + " ".join(errors)
        )


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def project_version():
    configured_version = os.getenv("APP_VERSION", "").strip()
    if configured_version:
        return configured_version

    for version_file in (BASE_DIR / "VERSION", BASE_DIR.parent / "VERSION"):
        if version_file.is_file():
            version = version_file.read_text(encoding="utf-8").strip()
            if version:
                return version

    raise ImproperlyConfigured("LanGuard VERSION file is missing or empty.")


ENVIRONMENT = os.getenv("ENVIRONMENT", "development").strip().lower()
APP_VERSION = project_version()
LATEST_VERSION_URL = os.getenv(
    "LATEST_VERSION_URL",
    "https://raw.githubusercontent.com/hillaliy/LanGuard/main/VERSION",
)
VERSION_CHECK_TIMEOUT = float(os.getenv("VERSION_CHECK_TIMEOUT", "3"))
VERSION_CHECK_INTERVAL = int(os.getenv("VERSION_CHECK_INTERVAL", "21600"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "unsafe-dev-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", default=False)

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    default=[
        "http://127.0.0.1:3000",
        "http://localhost:3000",
        "http://127.0.0.1:3001",
        "http://localhost:3001",
    ],
)

CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")

validate_production_settings(ENVIRONMENT, SECRET_KEY, DEBUG, ALLOWED_HOSTS)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "drf_spectacular",
]

SPECTACULAR_SETTINGS = {
    "TITLE": "LanGuard API",
    "DESCRIPTION": (
        "API documentation for LanGuard device discovery, port scanning, "
        "scan history, network events, and notification workflows."
    ),
    "VERSION": "v1",
    "SCHEMA_PATH_PREFIX": "/api/v1",
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = os.getenv("SECURE_REFERRER_POLICY", "same-origin")
SECURE_CROSS_ORIGIN_OPENER_POLICY = os.getenv(
    "SECURE_CROSS_ORIGIN_OPENER_POLICY",
    "same-origin",
)
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", default=False)
SESSION_COOKIE_SECURE = env_bool(
    "SESSION_COOKIE_SECURE",
    default=ENVIRONMENT == "production",
)
CSRF_COOKIE_SECURE = env_bool(
    "CSRF_COOKIE_SECURE",
    default=ENVIRONMENT == "production",
)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False
X_FRAME_OPTIONS = "DENY"

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.getenv("DB_PATH", BASE_DIR / "db.sqlite3"),
        "OPTIONS": {
            "timeout": int(os.getenv("SQLITE_TIMEOUT", "30")),
        },
    }
}

# User model and authentication
AUTH_USER_MODEL = "auth.User"
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.getenv("TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.getenv("STATIC_ROOT", BASE_DIR / "staticfiles")
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Logger settings
LOG_FILE = os.path.join(BASE_DIR, "log.log")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": LOG_FILE,
            "formatter": "verbose",
        },
    },
    "formatters": {
        "simple": {
            "format": "{asctime} : {levelname} - {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "verbose": {
            "format": "{asctime} : {levelname} - {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "core": {
            "handlers": ["file"],
            "level": "INFO",
            "propagate": True,
        },
    },
}


# Scan settings
IP_RANGE = os.getenv("IP_RANGE", "192.168.1.0/24")
INTERVAL = int(os.getenv("INTERVAL", "10"))
PORT_SCAN_ENABLED = env_bool("PORT_SCAN_ENABLED", default=True)
PORT_SCAN_PORTS = env_list(
    "PORT_SCAN_PORTS",
    default=[
        21,
        22,
        23,
        25,
        53,
        80,
        110,
        139,
        143,
        443,
        445,
        554,
        631,
        8080,
        8443,
        9100,
    ],
    cast=int,
)
PORT_SCAN_TIMEOUT = float(os.getenv("PORT_SCAN_TIMEOUT", "0.5"))
PORT_SCAN_INTERVAL = int(os.getenv("PORT_SCAN_INTERVAL", "30"))
SCAN_CONFIRM_OFFLINE_WITH_PORTS = env_bool("SCAN_CONFIRM_OFFLINE_WITH_PORTS", default=True)
SCAN_CONFIRM_OFFLINE_WITH_ICMP = env_bool("SCAN_CONFIRM_OFFLINE_WITH_ICMP", default=True)
SCAN_ICMP_TIMEOUT = float(os.getenv("SCAN_ICMP_TIMEOUT", "0.5"))
SCAN_ARP_TIMEOUT = float(os.getenv("SCAN_ARP_TIMEOUT", "2"))
SCAN_ARP_RETRIES = int(os.getenv("SCAN_ARP_RETRIES", "2"))
SCAN_OFFLINE_AFTER_MISSES = int(os.getenv("SCAN_OFFLINE_AFTER_MISSES", "3"))
SCAN_MOBILE_OFFLINE_AFTER_MISSES = int(os.getenv("SCAN_MOBILE_OFFLINE_AFTER_MISSES", "1"))
SCAN_SLEEPING_OFFLINE_AFTER_MISSES = int(os.getenv("SCAN_SLEEPING_OFFLINE_AFTER_MISSES", "6"))
SCAN_MAX_HOSTS = int(os.getenv("SCAN_MAX_HOSTS", "256"))
SCAN_ALLOW_PUBLIC_RANGES = env_bool("SCAN_ALLOW_PUBLIC_RANGES", default=False)
PORT_SCAN_MAX_PORTS = int(os.getenv("PORT_SCAN_MAX_PORTS", "64"))

# Notifications
NOTIFICATIONS_ENABLED = env_bool("NOTIFICATIONS_ENABLED", default=True)
NOTIFICATION_TIMEOUT = float(os.getenv("NOTIFICATION_TIMEOUT", "5"))
NOTIFICATION_RETRY_INTERVAL = int(os.getenv("NOTIFICATION_RETRY_INTERVAL", "15"))
NOTIFICATION_MAX_ATTEMPTS = int(os.getenv("NOTIFICATION_MAX_ATTEMPTS", "3"))
NOTIFICATION_EVENT_TYPES = env_list("NOTIFICATION_EVENT_TYPES", default=["new_device"])
DISCORD_WEBHOOK = os.getenv("DISCORD_WEBHOOK")
DISCORD_ICON_URL = os.getenv(
    "DISCORD_ICON_URL",
    f"https://raw.githubusercontent.com/hillaliy/LanGuard/main/frontend/public/logo.png?v={APP_VERSION}",
)
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
TELEGRAM_USERID = os.getenv("TELEGRAM_USERID")
