# Generated by Django 4.2.7 on 2023-11-20 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('ip', models.TextField()),
                ('mac', models.TextField()),
                ('vendor', models.TextField()),
                ('online', models.BooleanField(default=True)),
                ('lastseen', models.DateTimeField(default=django.utils.timezone.now)),
                ('known', models.BooleanField(default=False)),
            ],
        ),
    ]
