# Generated by Django 6.0.6 on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_device_scan_stability"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(
                        default=1,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("ip_range", models.CharField(default="192.168.1.0/24", max_length=64)),
                ("scan_interval", models.PositiveIntegerField(default=10)),
                ("notifications_enabled", models.BooleanField(default=True)),
                ("discord_webhook", models.URLField(blank=True, default="")),
                ("telegram_token", models.CharField(blank=True, default="", max_length=255)),
                ("telegram_user_id", models.CharField(blank=True, default="", max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "App settings",
                "verbose_name_plural": "App settings",
            },
        ),
    ]
