# Generated by Django 6.0.6 on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_appsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="time_zone",
            field=models.CharField(default="UTC", max_length=64),
        ),
    ]
