# Generated by Django 6.0.6 on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_appsettings_time_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="discord_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="telegram_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
