# Generated by Django 6.0.7 on 2026-08-30 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_device_identity_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='adguard_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='adguard_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='adguard_last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='adguard_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='adguard_retention_days',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='adguard_sync_interval',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='adguard_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='adguard_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='DeviceDNSActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253)),
                ('query_type', models.CharField(blank=True, default='', max_length=16)),
                ('query_count', models.PositiveBigIntegerField(default=0)),
                ('blocked_count', models.PositiveBigIntegerField(default=0)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('last_status', models.CharField(blank=True, default='', max_length=32)),
                ('last_reason', models.CharField(blank=True, default='', max_length=64)),
                ('last_service_name', models.CharField(blank=True, default='', max_length=128)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_activity', to='core.device')),
            ],
            options={
                'ordering': ['-last_seen', 'domain', 'query_type'],
                'indexes': [models.Index(fields=['device', '-last_seen'], name='core_dns_device_seen_idx'), models.Index(fields=['device', '-blocked_count'], name='core_dns_device_blocked_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'domain', 'query_type'), name='unique_device_dns_domain_type')],
            },
        ),
    ]
