# Generated by Django 6.0.7 on 2026-08-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_adguard_unmatched_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='webhook_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='webhook_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='channel',
            field=models.CharField(choices=[('discord', 'Discord'), ('telegram', 'Telegram'), ('webhook', 'Webhook')], max_length=32),
        ),
    ]
