# Generated by Django 6.0.7 on 2026-09-01 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grant_existing_users_access(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    UserAccess = apps.get_model("core", "UserAccess")
    UserAccess.objects.bulk_create(
        [UserAccess(user_id=user_id) for user_id in User.objects.values_list("id", flat=True)],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_appsettings_webhook_enabled_appsettings_webhook_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit_devices', models.BooleanField(default=True)),
                ('can_edit_home_map', models.BooleanField(default=True)),
                ('can_run_scans', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='languard_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User access',
                'verbose_name_plural': 'User access',
            },
        ),
        migrations.RunPython(grant_existing_users_access, migrations.RunPython.noop),
    ]
