# Generated by Django 6.0.7 on 2026-09-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_useraccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='speedtest_tracker_api_token',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='speedtest_tracker_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='speedtest_tracker_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
    ]
