# Generated by Django 6.0.7 on 2026-09-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_scan_range_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='homebox_api_token',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='homebox_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='homebox_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='device',
            name='homebox_item_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
