# Generated by Django 6.0.7 on 2026-09-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_homebox_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
