# Generated by Django 6.0.7 on 2026-09-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_device_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkevent',
            name='event_type',
            field=models.CharField(choices=[('new_device', 'New device'), ('device_online', 'Device online'), ('device_offline', 'Device offline'), ('ip_changed', 'IP changed'), ('port_opened', 'Port opened'), ('port_closed', 'Port closed')], max_length=32),
        ),
    ]
