# Generated by Django 6.0.7 on 2026-09-11 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_networkevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='last_notified_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='notify_version_updates',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='networkevent',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.device'),
        ),
        migrations.AlterField(
            model_name='networkevent',
            name='event_type',
            field=models.CharField(choices=[('new_device', 'New device'), ('device_online', 'Device online'), ('device_offline', 'Device offline'), ('ip_changed', 'IP changed'), ('version_available', 'Version available'), ('port_opened', 'Port opened'), ('port_closed', 'Port closed')], max_length=32),
        ),
    ]
