# Generated by Django 6.0.7 on 2026-09-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_appsettings_last_notified_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_visitor',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(condition=models.Q(('is_visitor', False), ('known', True), _connector='OR'), name='visitor_device_must_be_known'),
        ),
    ]
