# Generated by Django 6.0.7 on 2026-09-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_device_is_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='notify_speedtest_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='speedtest_last_healthy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='speedtest_last_result_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='networkevent',
            name='event_type',
            field=models.CharField(choices=[('new_device', 'New device'), ('device_online', 'Device online'), ('device_offline', 'Device offline'), ('ip_changed', 'IP changed'), ('version_available', 'Version available'), ('speedtest_health_changed', 'Speedtest health changed'), ('port_opened', 'Port opened'), ('port_closed', 'Port closed')], max_length=32),
        ),
    ]
