# Generated by Django 6.0.7 on 2026-09-24 05:20

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def open_current_ip_assignments(apps, schema_editor):
    Device = apps.get_model("core", "Device")
    DeviceIPAddressAssignment = apps.get_model(
        "core",
        "DeviceIPAddressAssignment",
    )
    migrated_at = timezone.now()
    DeviceIPAddressAssignment.objects.bulk_create(
        [
            DeviceIPAddressAssignment(
                device_id=device.pk,
                ip=device.ip,
                valid_from=migrated_at,
            )
            for device in Device.objects.all().iterator()
        ],
        batch_size=500,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_device_external_url_follow_device_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceIPAddressAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True)),
                ('valid_from', models.DateTimeField(db_index=True)),
                ('valid_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_assignments', to='core.device')),
            ],
            options={
                'ordering': ['-valid_from', '-id'],
                'indexes': [models.Index(fields=['ip', 'valid_from', 'valid_until'], name='core_ip_assignment_lookup_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('valid_until__isnull', True)), fields=('device',), name='unique_active_device_ip_assignment'), models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='device_ip_assignment_valid_range')],
            },
        ),
        migrations.RunPython(
            open_current_ip_assignments,
            migrations.RunPython.noop,
        ),
    ]
