# Generated by Django 6.0.7 on 2026-09-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_scanrun_locking'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='offline_attention_after_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='presence_expectation',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('always', 'Always expected'), ('occasional', 'Occasionally present'), ('never', 'Do not monitor absence')], default='automatic', max_length=16),
        ),
    ]
