# Generated by Django 6.0.7 on 2026-09-28 10:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_device_offline_attention_after_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkevent',
            name='event_type',
            field=models.CharField(choices=[('new_device', 'New device'), ('device_online', 'Device online'), ('device_offline', 'Device offline'), ('ip_changed', 'IP changed'), ('version_available', 'Version available'), ('speedtest_health_changed', 'Speedtest health changed'), ('port_opened', 'Port opened'), ('port_closed', 'Port closed'), ('container_discovered', 'Container discovered'), ('container_port_exposed', 'Container port exposed')], max_length=32),
        ),
        migrations.CreateModel(
            name='DockerHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('sync_interval', models.PositiveIntegerField(default=5)),
                ('sync_requested', models.BooleanField(default=True)),
                ('docker_name', models.CharField(blank=True, default='', max_length=255)),
                ('docker_version', models.CharField(blank=True, default='', max_length=64)),
                ('operating_system', models.CharField(blank=True, default='', max_length=255)),
                ('architecture', models.CharField(blank=True, default='', max_length=64)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docker_host', to='core.device')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DockerContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, default='', max_length=512)),
                ('image_id', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=32)),
                ('health', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('network_mode', models.CharField(blank=True, default='', max_length=64)),
                ('addresses', models.JSONField(blank=True, default=list)),
                ('published_ports', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('restart_count', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('linked_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docker_containers', to='core.device')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='core.dockerhost')),
            ],
            options={
                'ordering': ['name', 'container_id'],
                'indexes': [models.Index(fields=['host', 'active'], name='core_docker_host_active_idx'), models.Index(fields=['linked_device', 'active'], name='core_docker_device_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('host', 'container_id'), name='unique_docker_container_per_host')],
            },
        ),
    ]
