# Generated by Django 6.0.7 on 2026-09-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_scanrun_failure_diagnostics'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='devicednsactivity',
            name='unique_device_dns_domain_type',
        ),
        migrations.AddField(
            model_name='adguardunmatchedclient',
            name='provider',
            field=models.CharField(db_index=True, default='adguard', max_length=16),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='pihole_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='pihole_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='pihole_last_query_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='pihole_last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='pihole_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='pihole_retention_days',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='pihole_sync_interval',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='pihole_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='devicednsactivity',
            name='provider',
            field=models.CharField(db_index=True, default='adguard', max_length=16),
        ),
        migrations.AlterField(
            model_name='adguardunmatchedclient',
            name='client',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname_source',
            field=models.CharField(blank=True, choices=[('reverse_dns', 'Reverse DNS'), ('mdns', 'mDNS'), ('llmnr', 'LLMNR'), ('netbios', 'NetBIOS'), ('ssdp', 'SSDP / UPnP'), ('snmp', 'SNMP'), ('http', 'Device web interface'), ('arp', 'ARP'), ('manuf', 'Wireshark manuf'), ('inferred', 'Inferred'), ('imported', 'Imported inventory'), ('pihole', 'Pi-hole DHCP')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor_source',
            field=models.CharField(blank=True, choices=[('reverse_dns', 'Reverse DNS'), ('mdns', 'mDNS'), ('llmnr', 'LLMNR'), ('netbios', 'NetBIOS'), ('ssdp', 'SSDP / UPnP'), ('snmp', 'SNMP'), ('http', 'Device web interface'), ('arp', 'ARP'), ('manuf', 'Wireshark manuf'), ('inferred', 'Inferred'), ('imported', 'Imported inventory'), ('pihole', 'Pi-hole DHCP')], default='', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='adguardunmatchedclient',
            constraint=models.UniqueConstraint(fields=('provider', 'client'), name='unique_dns_provider_unmatched_client'),
        ),
        migrations.AddConstraint(
            model_name='devicednsactivity',
            constraint=models.UniqueConstraint(fields=('provider', 'device', 'domain', 'query_type'), name='unique_device_dns_domain_type'),
        ),
    ]
