# Generated by Django 6.1.1 on 2026-10-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0046_remove_devicednsactivity_unique_device_dns_domain_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="snmp_community",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="snmp_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="device",
            name="snmp_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="device",
            name="snmp_last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
