# Generated by Django 6.1.1 on 2026-10-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_snmp_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='technitium_api_token',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='technitium_dhcp_create_devices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='technitium_dhcp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='technitium_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='technitium_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='technitium_last_query_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='technitium_last_query_row',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='technitium_last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='technitium_last_sync_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='technitium_retention_days',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='technitium_sync_interval',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='technitium_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname_source',
            field=models.CharField(blank=True, choices=[('reverse_dns', 'Reverse DNS'), ('mdns', 'mDNS'), ('llmnr', 'LLMNR'), ('netbios', 'NetBIOS'), ('ssdp', 'SSDP / UPnP'), ('snmp', 'SNMP'), ('http', 'Device web interface'), ('arp', 'ARP'), ('manuf', 'Wireshark manuf'), ('inferred', 'Inferred'), ('imported', 'Imported inventory'), ('pihole', 'Pi-hole DHCP'), ('technitium', 'Technitium DHCP')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor_source',
            field=models.CharField(blank=True, choices=[('reverse_dns', 'Reverse DNS'), ('mdns', 'mDNS'), ('llmnr', 'LLMNR'), ('netbios', 'NetBIOS'), ('ssdp', 'SSDP / UPnP'), ('snmp', 'SNMP'), ('http', 'Device web interface'), ('arp', 'ARP'), ('manuf', 'Wireshark manuf'), ('inferred', 'Inferred'), ('imported', 'Imported inventory'), ('pihole', 'Pi-hole DHCP'), ('technitium', 'Technitium DHCP')], default='', max_length=32),
        ),
    ]
