# Generated by Django 6.1.1 on 2026-10-08 06:23

from django.db import migrations, models


def preserve_configured_pihole_behavior(apps, schema_editor):
    app_settings = apps.get_model('core', 'AppSettings')
    app_settings.objects.exclude(pihole_url='').update(
        pihole_dhcp_enabled=True,
        pihole_dhcp_create_devices=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_appsettings_technitium_api_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='pihole_dhcp_create_devices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='pihole_dhcp_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(
            preserve_configured_pihole_behavior,
            migrations.RunPython.noop,
        ),
    ]
