# Generated by Django 6.1.1 on 2026-10-09 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_appsettings_pihole_dhcp_create_devices_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='merged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='merged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_interface_merges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_interfaces', to='core.device'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(condition=models.Q(('merged_into', models.F('id')), _negated=True), name='device_cannot_merge_into_itself'),
        ),
        migrations.AlterField(
            model_name='networkevent',
            name='event_type',
            field=models.CharField(choices=[('new_device', 'New device'), ('device_online', 'Device online'), ('device_offline', 'Device offline'), ('ip_changed', 'IP changed'), ('version_available', 'Version available'), ('speedtest_health_changed', 'Speedtest health changed'), ('port_opened', 'Port opened'), ('port_closed', 'Port closed'), ('container_discovered', 'Container discovered'), ('container_port_exposed', 'Container port exposed'), ('device_interfaces_merged', 'Device interfaces merged'), ('device_interface_separated', 'Device interface separated')], max_length=32),
        ),
    ]
